# Reusable Workflow managing Publishing Test
name: Test
on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      repo_org:
        required: true
        type: string
      other_repo_to_delete:
        type: string
    secrets:
      TEST_TOKEN:
        required: true

permissions: read-all

jobs:
  test_prerequisite:
    name: Prerequisite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Local Repo
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Clean Previous Test Data
        run: |
          gh repo delete "${REPO_ORG}/${REPO_NAME}" --yes || true
          readarray -t repos <<<"${OTHER_REPO_TO_DELETE}"
          for repo in "${repos[@]}"
          do
            gh repo delete "${repo}" --yes || true
          done
        env:
          GH_TOKEN: ${{ secrets.TEST_TOKEN }}
          REPO_ORG: ${{ inputs.repo_org }}
          REPO_NAME: ${{ inputs.repo_name }}
          OTHER_REPO_TO_DELETE: ${{ inputs.other_repo_to_delete }}

      - name: Create repository
        shell: bash
        run: |
          gh repo create "${REPOSITORY}" --public --add-readme
        env:
          GH_TOKEN: "${{ secrets.TEST_TOKEN }}"
          REPOSITORY: "${{ inputs.repo_org }}/${{ inputs.repo_name }}"

      - name: Checkout Repository
        id: checkout_template
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          repository: ${{ inputs.repo_org }}/${{ inputs.repo_name }}
          path: ${{ inputs.repo_name }}
          token: ${{ secrets.TEST_TOKEN }}
          persist-credentials: false

      - name: Copy test workflow & content
        id: copy_content
        shell: bash
        run: |
          cp -r ./test/create_template_action/template/. "${REPO_NAME}"/
          uuid="$(uuidgen)"
          echo "$uuid" > "${REPO_NAME}"/"${TEST_UUID_FILENAME}"
          echo "uuid=${uuid}" >> "$GITHUB_OUTPUT"
        env:
          REPO_NAME: ${{ inputs.repo_name }}
          TEST_UUID_FILENAME: ${{ vars.TEST_UUID_FILENAME }}

      - name: Commit & Push changes To Repository
        uses: actions-js/push@968f4695ca558093eadb24ad83cc5891f47e0cdc # master
        with:
          github_token: "${{ secrets.TEST_TOKEN }}"
          directory: ${{ inputs.repo_name }}
          repository: ${{ inputs.repo_org }}/${{ inputs.repo_name }}
