name: AutoInit Prerequisite
on:
  workflow_call:
    outputs:
      uuid:
        value: ${{ jobs.autoinit_prerequisite.outputs.uuid }}
    secrets:
      TEST_TOKEN:
        required: true
      TESTSPACE_TOKEN:
        required: true

jobs:
  autoinit_prerequisite:
    name: Prerequisite
    runs-on: ubuntu-latest
    outputs:
      uuid: ${{ steps.create_autoinit.outputs.uuid }}
    steps:
        - name: Clean Test Data
          env:
            GH_TOKEN: ${{ secrets.TEST_TOKEN }}
          run: |
            gh repo delete ${{ vars.TEST_AUTOINIT_REPO_ORG }}/${{ vars.TEST_AUTOINIT_REPO_NAME }} --yes || true

        - name: Checkout Local Repo
          id: checkout
          uses: actions/checkout@v4

        - name: Create AutoInit repository
          id: create_autoinit
          uses: ./test/create_template_action/
          with:
            repo_name: ${{ vars.TEST_AUTOINIT_REPO_NAME }}
            repo_org: ${{ vars.TEST_AUTOINIT_REPO_ORG }}
            token: ${{ secrets.TEST_TOKEN }}
            uuid_filename: ${{ vars.TEST_UUID_FILENAME }}
            is_template: false
  
        - name: Add Secret To AutoInit repository
          run: |
            gh secret set TEST_TOKEN --repo ${{ vars.TEST_AUTOINIT_REPO_ORG }}/${{ vars.TEST_AUTOINIT_REPO_NAME }} --body "${{ secrets.TEST_TOKEN }}"
            gh secret set TESTSPACE_TOKEN --repo ${{ vars.TEST_AUTOINIT_REPO_ORG }}/${{ vars.TEST_AUTOINIT_REPO_NAME }} --body "${{ secrets.TESTSPACE_TOKEN }}"
          env:
            GH_TOKEN: ${{ secrets.TEST_TOKEN }}