name: Prerequisite
on:
  workflow_call:
    outputs:
      uuid:
        value: ${{ jobs.tool_prerequisite.outputs.uuid }}
    secrets:
      TEST_TOKEN:
        required: true

jobs:
  tool_prerequisite:
    name: Prerequisite
    runs-on: ubuntu-latest
    outputs:
      uuid: ${{ steps.create_template.outputs.uuid }}
    steps:
        - name: Clean Test Data
          env:
            GH_TOKEN: ${{ secrets.TEST_TOKEN }}
          run: |
            gh repo delete ${{ vars.TEST_TEMPLATE_REPO_ORG}}/${{ vars.TEST_TEMPLATE_REPO_NAME }} --yes || true
            gh repo delete ${{ vars.TEST_PUBLISHED_REPO_ORG }}/${{ vars.TEST_PUBLISHED_REPO_NAME }} --yes || true
            gh repo delete ${{ vars.TEST_NEW_REPO_ORG }}/${{ vars.TEST_NEW_REPO_NAME }} --yes || true

        - name: Create Published repository
          uses: f1lander/create-repository-action@v1.0.2
          with:
            name: '${{ vars.TEST_PUBLISHED_REPO_NAME }}'
            org: '${{ vars.TEST_PUBLISHED_REPO_ORG }}'
            access-token: '${{ secrets.TEST_TOKEN }}'

        - name: Checkout Local Repo
          id: checkout
          uses: actions/checkout@v4

        - name: Create Template repository
          id: create_template
          uses: ./test/create_template_action/
          with:
            repo_name: ${{ vars.TEST_TEMPLATE_REPO_NAME }}
            repo_org: ${{ vars.TEST_TEMPLATE_REPO_ORG }}
            token: ${{ secrets.TEST_TOKEN }}
            uuid_filename: ${{ vars.TEST_UUID_FILENAME }}