name: "Tags"
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions: read-all

jobs:
  tags:
    runs-on: ubuntu-latest
    name: "Additional Tags"
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: vweevers/additional-tags-action@3bab55b44e81186dcfef7db9f2cbca01a78eb710 # v2
