name: 'Functional Tests'

on:
  push:

# Needed Global vars (to can be used in local nested reusable workflow)
# - TEST_TEMPLATE_REPO_NAME
# - TEST_TEMPLATE_REPO_ORG
# - TEST_TEMPLATE_LOCAL_DIR
# - TEST_PUBLISHED_REPO_NAME
# - TEST_PUBLISHED_REPO_ORG
# - TEST_NEW_REPO_NAME
# - TEST_NEW_REPO_ORG
# - TEST_UUID_FILENAME: test.txt
# - TEST_AUTOINIT_REPO_NAME
# - TEST_AUTOINIT_REPO_ORG

jobs:
  test_tool:
    name: Tool
    uses: ./.github/workflows/_test_tool_all.yml
    secrets: inherit

  test_autoinit:
    name: AutoInit
    uses: ./.github/workflows/_test_autoinit.yml
    secrets: inherit

  clean:
    if: always()
    name: Clean
    needs: [test_tool,test_autoinit]
    runs-on: ubuntu-latest
    steps:
      - name: Clean Test Data
        env:
          GH_TOKEN: ${{ secrets.TEST_TOKEN }}
        run: |
          gh repo delete ${{ vars.TEST_TEMPLATE_REPO_ORG}}/${{ vars.TEST_TEMPLATE_REPO_NAME }} --yes || true
          gh repo delete ${{ vars.TEST_PUBLISHED_REPO_ORG }}/${{ vars.TEST_PUBLISHED_REPO_NAME }} --yes || true
          gh repo delete ${{ vars.TEST_NEW_REPO_ORG }}/${{ vars.TEST_NEW_REPO_NAME }} --yes || true
          gh repo delete ${{ vars.TEST_AUTOINIT_REPO_ORG }}/${{ vars.TEST_AUTOINIT_REPO_NAME }} --yes || true

  report:
    if: always()
    name: Save Test Resut
    needs: [test_tool,test_autoinit]
    runs-on: ubuntu-latest
    steps:
      # Need to checkout to give context to testspace cli
      - name: Checkout Local Repo
        id: checkout
        uses: actions/checkout@v4
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - name: Testspace client install & config
        id: testspace_init
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.repository_owner }}
      - name: Testspace push test content
        run: |
          output=$(testspace "[Integ Tests]./**/report.xml")
          # echo "::notice::$toto"
          REGEX="(https://[a-z0-9]+.testspace.com/spaces/[0-9]+/result_sets/[0-9]+)"
          [[ $output =~ $REGEX ]]
          result_set_link="${BASH_REMATCH[1]}"
          echo "[TestSpace Test Result set]($result_set_link)" >> $GITHUB_STEP_SUMMARY
